### ISSUE TITLE
Error: fun must return a single number per group

### ISSUE THREAD

**Issue by geneanalyst** [tidyverse/forcats#103]
Got the following error:

Error: fun must return a single number per group

After running the following:

test$POPULATION <- factor(test$POPULATION) %>%
  fct_reorder(test$EXCESS_ALLELE_MATCHES_WITH_MBUTI, .desc = TRUE)

Where the data frame test is a 3 column file with header:

POPULATION  EXCESS_ALLELE_MATCHES_WITH_MBUTI    GROUP
Jordanian   1,059   W Asians
BedouinB    937 W Asians
Saudi   894 W Asians
GujaratiD   835 S/SC Asians
Druze   722 W Asians
Iran_Fars   704 W Asians
Pathan  660 S/SC Asians

**Comment by cderv** [comment]
Hi, 

You got the error because you did not provide a `fun` argument in `fct_reorder` that works. By default, it calls `fun=median` and as the error said it expects a single number per group. 
In your case, you applied `median` to `EXCESS_ALLELE_MATCHES_WITH_MBUTI` that is a character vector. It does not return a number.  

You need to think through with what you want to do. You can help us help you by making a [reproductible example](http://reprex.tidyverse.org/). 

Here is a reprex with you data and some transformation. You see that if the column is numeric, it works and factor is reordered. 

``` r
library(dplyr, warn.conflicts = FALSE)
test <- tribble(
  ~ POPULATION, ~ EXCESS_ALLELE_MATCHES_WITH_MBUTI, ~ GROUP,
  "Jordanian", "1,059 W", "Asians",
  "BedouinB", "937 W", "Asians",
  "Saudi", "894 W", "Asians",
  "GujaratiD", "835 S/SC", "Asians",
  "Druze", "722 W", "Asians",
  "Iran_Fars", "704 W", "Asians",
  "Pathan", "660 S/SC", "Asians"
) %>%
  mutate(
    # Second column is parsed as numeric
    EXCESS_ALLELE_MATCHES_WITH_MBUTI_NUM = readr::parse_number(EXCESS_ALLELE_MATCHES_WITH_MBUTI),
    # POPULATION is parsed as factor
    POPULATION = factor(POPULATION))

library(forcats)

# Levels before reorder
levels(test$POPULATION)
#> [1] "BedouinB"  "Druze"     "GujaratiD" "Iran_Fars" "Jordanian" "Pathan"   
#> [7] "Saudi"
# Levels are reordered base on your data
test$POPULATION %>%
  fct_reorder(test$EXCESS_ALLELE_MATCHES_WITH_MBUTI_NUM, .desc = TRUE) %>%
  levels()
#> [1] "Jordanian" "BedouinB"  "Saudi"     "GujaratiD" "Druze"     "Iran_Fars"
#> [7] "Pathan"
```

Created on 2018-01-08 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).
