### ISSUE TITLE
Inconsistent argument names in the various forcats functions

### ISSUE THREAD

**Issue by huftis** [tidyverse/forcats#121]
The various factor functions in `forcats` use different names for their first argument (the input factor). For example, `fct_inorder` uses `f`, `fct_relabel` uses `.f` and `fct_union` uses `fs` (though perhaps the last one makes sense, since the input is a *list* of factors). They should be consistent, because of, er, consistency’s sake.

Here’s a reprex, showing the frequency of the various first arguments:

```r
library(forcats)
x = lsf.str("package:forcats")
x %>% purrr::map_chr(~formals(.) %>% names() %>% dplyr::first()) %>%
  table %>%
  sort(decreasing = TRUE)
#> .
#>   f  .f  fs ...  .x lhs   x 
#>  16   6   2   1   1   1   1
```

**Comment by batpigandme** [comment]
At least in the cases you've mentioned, I believe this is because they work differently. With [`fct_relabel()`](https://github.com/tidyverse/forcats/blob/master/R/relabel.R), for example, you're mapping the function over each level of a factor, `.f`. 

The same is true of `fct_reorder()` where you're mapping the order by a function:
https://github.com/tidyverse/forcats/blob/f4a7fd1d65b8096433d8dd18bf77293e1541c8b9/R/reorder.R#L40

However, with `fct_inorder()` you're just passing it the factor. There is no other argument (function) that you are mapping over the factor.
https://github.com/tidyverse/forcats/blob/f4a7fd1d65b8096433d8dd18bf77293e1541c8b9/R/reorder.R#L85

**Comment by hadley** [comment]
It's probably worth trying to be a bit more consistent here, but the risk of breaking existing code means that it needs to be done with care.

**Comment by hadley** [comment]
``` r
library(forcats)
library(purrr)

ls("package:forcats") %>% 
  set_names() %>% 
  map(get) %>% 
  keep(is.function) %>% 
  map(formals) %>% 
  map(names) %>% 
  map_chr(1) %>% 
  split(names(.), .)
#> $...
#> [1] "fct_c"
#> 
#> $.f
#> [1] "fct_collapse" "fct_cross"    "fct_recode"   "fct_relabel" 
#> [5] "fct_relevel"  "fct_reorder"  "fct_reorder2"
#> 
#> $.x
#> [1] "last2"
#> 
#> $f
#>  [1] "fct_anon"        "fct_count"       "fct_drop"       
#>  [4] "fct_expand"      "fct_explicit_na" "fct_infreq"     
#>  [7] "fct_inorder"     "fct_lump"        "fct_lump_min"   
#> [10] "fct_other"       "fct_rev"         "fct_shift"      
#> [13] "fct_shuffle"     "fct_unique"      "lvls_expand"    
#> [16] "lvls_reorder"    "lvls_revalue"   
#> 
#> $fs
#> [1] "fct_unify"  "lvls_union"
#> 
#> $lhs
#> [1] "%>%"
#> 
#> $x
#> [1] "as_factor"
```

<sup>Created on 2019-02-16 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

Reviewing these names, I think the only real problem is `last2()`, but it's so specialised it doesn't seem worth bothering with.
